### ISSUE TITLE
Colorize in VS Code [only Flutter projects]

### ISSUE THREAD

**Issue by vico-aguado** [jorgecoca/lumberdash#10]
Hi! I can´t printing properly in Visual Studio Code :( see:
<img width="582" alt="Screen Shot 2019-03-12 at 2 34 55 PM" src="https://user-images.githubusercontent.com/22483705/54234293-6fbe2a80-44d4-11e9-9fdd-1b4e07073b9e.png">
Could you help me, please?

**Comment by jorgecoca** [comment]
Interesting, I don't have problems with a pure Dart project, but I do with a Flutter project... will take a look...

**Comment by jorgecoca** [comment]
I believe it is an issue on the Flutter side, since they modify the message to prepend `flutter: ` to the message. 

I have opened this issue to follow up: https://github.com/flutter/flutter/issues/29255

**Comment by jgroman** [comment]
BTW works fine on Windows/Android combo with current stable Flutter 1.2.1
![lumber](https://user-images.githubusercontent.com/28655510/54485973-05b1d680-4882-11e9-8a79-773fd8c00412.png)

**Comment by jgroman** [comment]
This might be iOS only problem: https://github.com/flutter/flutter/issues/20663

**Comment by jorgecoca** [comment]
@vico-aguado @jgroman fixed on 1.1.0! Thank you for your help!

**Comment by mirkancal** [comment]
I have the same problem. I'm using ubuntu

```
[✓] VS Code (version 1.35.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.1.0
```

**Comment by jamieastley** [comment]
I'm still getting the same issue as OP on v1.1.0.

Running Flutter in VSCode on MacOS 10.14.6 and building to Simulator (if that's relevant to know).

**Comment by gcostaapps** [comment]
@jorgecoca I have the same problem in the current version of the package and flutter

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.54.3)
[√] Connected device (4 available)
```

![image](https://user-images.githubusercontent.com/65033296/112739757-4783b600-8f4d-11eb-866d-a03fdb5f5ac8.png)
