### ISSUE TITLE
[firebase_lumberdash] dependecy check fails with firebase_analytics 3.0.0

### ISSUE THREAD

**Issue by jamieastley** [jorgecoca/lumberdash#19]
> Because {project} depends on firebase_lumberdash ^1.0.0 which depends on firebase_analytics ^2.1.1, firebase_analytics ^2.1.1 is required.
So, because {project} depends on firebase_analytics 3.0.0, version solving failed.

Is support possible for the latest Firebase Analytics package please?

**Comment by jorgecoca** [comment]
Thanks for opening the issue!

Yes, I'll try to update it during the weekend.

**Comment by jorgecoca** [comment]
@jamie1192 you can find a `1.0.1` version here: https://pub.dev/packages/firebase_lumberdash

**Comment by jamieastley** [comment]
super late response getting back to this, but thanks for the update!
