### ISSUE TITLE
[lumberdash v2] Better design spec

### ISSUE THREAD

**Issue by jorgecoca** [jorgecoca/lumberdash#28]
As a result of #27 , we realized that the existing API is not as flexible as we thought it would be, and that it might be tailor made to `Sentry`.

Let's use this thread to propose a new/better API, and release a v2.

Requirements are:

* Ability to use multiple clients (simple, color, sentry, firebase...)
* Decide on a naming convention for the API
* Decide what's needed vs optional
* Better and complete documentation

Open questions:

* Should we separate plugins into its own repos?

@felangel @XinfengMa @erickjtorres  FYI

**Comment by jorgecoca** [comment]
One of the requests would be easy to accomodate: supporting multiple clients at once. I think the simplest solution would be this:

`putLumberdastToWork(List<LumberdashClient> clients)` 

This would solve #29 by giving a list of clients, and #23 (no-op) client, by passing an empty list.

Will still need to think about a better logging API.

**Comment by Paul-Todd** [comment]
That would work - if we call it a second time with a new list would it replace the existing list of clients?

**Comment by jorgecoca** [comment]
@Paul-Todd would you give us a use case for calling `putLumberdashToWork` for a second time? In my mind, I think this method should be seen as an `init/setup` config, so it should be called only one time...

**Comment by jorgecoca** [comment]
Development will start on branch https://github.com/bmw-tech/lumberdash/tree/feature/version2

**Comment by jorgecoca** [comment]
v2 has been released!!!!! 🎉

All plugins have been updated!!!! 👩‍💻👨‍💻
