### ISSUE TITLE
Support for multiple clients

### ISSUE THREAD

**Issue by Paul-Todd** [jorgecoca/lumberdash#29]
Hi,

How can I have support for multiple plugins. For example I would like to use the Firebase and the Colorize plugin together so that logging is done to the console and also to FireBase

**Comment by jorgecoca** [comment]
Hi @Paul-Todd 👋 

At this moment, v1 does not support this functionality, but I think it is a valid feature, so I will tag it for `v2`, which is in the works right now ;)

Thank you!

**Comment by jorgecoca** [comment]
@Paul-Todd v2 has been merged to master with support for multiple clients. Any feedback is welcomed ;)
