### ISSUE TITLE
Add support for new Firebase analytics major release (6.x.x)

### ISSUE THREAD

**Issue by spicybackend** [jorgecoca/lumberdash#55]
Not sure how much the API has changed at all, but the lumberdash Firebase plugin is now unable to be used with the latest version of Firebase analytics.
```
# flutter pub get output
Because firebase_lumberdash >=2.0.0 depends on firebase_analytics ^5.0.2 and app depends on firebase_analytics ^6.0.0, firebase_lumberdash >=2.0.0 is forbidden.
```

**Comment by fwagner** [comment]
With v3.0.0 we are supporting firebase 7.1, I guess we can close this issue.
