### ISSUE TITLE
[sentry_lumberdash] sentry >=3.0.0 not supported

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [jorgecoca/lumberdash#59]
The `3.0.0` release of the `sentry` package added web support: https://pub.dev/packages/sentry/changelog#300

`sentry_lumberdash` does not support the new `sentry` versions.

**Comment by jamieastley** [comment]
Since this has been fixed in the above linked merged PR, could someone please publish the package update to pub.dev?

**Comment by fwagner** [comment]
The above change was published as part of v3.0.0 on Monday.
