### ISSUE TITLE
[lumberdash] Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [jorgecoca/lumberdash#61]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:lumberdash`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by IchordeDionysos** [comment]
@fwagner you are currently working on the null-safe version, did I see this correctly? 🤔 

What are your plans/rough timeline (without guarantees obviously) for publishing the version? ☺️

**Comment by fwagner** [comment]
There should be a release to pub.dev early next week. Next step is updating the appender packages ("plugins") which should be on pub.dev shortly after.

**Comment by IchordeDionysos** [comment]
Thank you very much 😍  Helps a lot

**Comment by fwagner** [comment]
lumberdash 3.0.0 has been published to pub. We'll use #62 to track updating the appenders/plugins.
