### ISSUE TITLE
[*_lumberdash] Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [jorgecoca/lumberdash#62]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:colorize_lumberdash` and other packages.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by fwagner** [comment]
Fixed by #68. New versions of all packages have been published to pub.
