### ISSUE TITLE
Update homepage in pubspec.yaml

### ISSUE THREAD

**Issue by IchordeDionysos** [jorgecoca/lumberdash#63]
You probably should update the homepage in the `pubspec.yaml` of `package:colorize_lumberdash`, `package:firebase_lumberdash`, `package:print_lumberdash`, `package:sentry_lumberdash` so it points to this repo and not your fork of the repo!

Otherwise, when clicking on "View/Report issues" on pub.dev everyone will be redirected to the fork of the repo and NOT this repo.

**Comment by fwagner** [comment]
Fixed by #68 and published.
